### ISSUE TITLE
Automation Support

### ISSUE THREAD

**Issue by Yowesephth** [HooferDevelops/url-music-discs#15]
These discs seem to only work when a player themselves manually puts the disc in.

I would at least suspect hoppers from vanilla to be able to make the jukebox play a custom disk.

Optimally, any source should get it to work, like a create mechanical arm.

(this is on fabric 0.15.6, for minecraft 1.20.1 and this mod on version 1.1.0)

**Comment by HooferDevelops** [comment]
This is addressed and resolved in version 1.2.0, thank you for the report!
