### ISSUE TITLE
[Question] Why Discord only?

### ISSUE THREAD

**Issue by No3371** [HooferDevelops/url-music-discs#2]
Apparently the mod is downloading files from the provided Discord CDN url just like any other url, I believe ffmpeg can handle more than that, and it's not guaranteed that a file from Discord CDN is in certain format or something. Out of curiosity, why?

Also I noticed its set to 64k bitrate, I wonder can we go for `bestaudio` for yt-dlp and 128k for ffmpeg.

**Comment by HooferDevelops** [comment]
I have it set to Discord & Youtube strictly for security reasons. If you allowed any URL, a threat actor could input an IP logger as a URL, which will attempted to be downloaded. In the future, I could add support for other URLs such as Dropbox and Github, but I don't see a reason to as Youtube is an option.

As for bitrate, I will look into adding a client config option for changing that. I have the bitrate low to make download sizes small for users.

**Comment by No3371** [comment]
👍 Valid point, I only thought about possibility of malicious files. Thanks!
